name: SonarCloud + GPT para Spring Boot

on:
  push:
    branches:
      - main

jobs:
  sonar-gpt-review:
    name: Análisis y revisión con GPT
    runs-on: ubuntu-latest
    env:
      MAX_ITERACIONES_CI: 5

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Caché de Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Compilar y testear el proyecto
        run: mvn clean verify

      - name: Análisis original con SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          echo "🔍 Ejecutando análisis Sonar original..."
          mvn sonar:sonar \
            -Dsonar.projectKey=rodrigorojasg_testSpring \
            -Dsonar.organization=rodrigorojasg \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.sources=src \
            -Dsonar.tests=src/test \
            -Dsonar.exclusions=src/test/** \
            -Dsonar.java.binaries=target/classes > salida_sonar_original.txt

          echo "=== Salida de Sonar ==="
          cat salida_sonar_original.txt

          errores_antes=$(grep -o 'severity":"[A-Z]\+"' salida_sonar_original.txt | wc -l || true)
          echo "ERRORES_ANTES=$errores_antes" >> $GITHUB_ENV

      - name: Obtener archivos con errores
        id: sonar_files
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          curl -s "https://sonarcloud.io/api/issues/search?componentKeys=rodrigorojasg_testSpring&resolved=false" \
            -H "Authorization: Bearer $SONAR_TOKEN" | \
            jq -r '.issues[].component' | sort -u > archivos_afectados.txt

      - name: Mejoras con GPT
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          mkdir -p reportes_ci
          iteracion=1
          echo "ITERACION_ACTUAL=$iteracion" >> $GITHUB_ENV

          while read COMPONENT; do
            FILE=$(echo "$COMPONENT" | sed 's/^rodrigorojasg_testSpring://')
            echo "Procesando: $FILE"

            if [ -f "$FILE" ]; then
              CODE=$(base64 "$FILE" | tr -d '\n')
              REPORT="Problemas detectados por SonarCloud en $COMPONENT"
              RESPONSE_FILE="reportes_ci/gpt_response_$(basename $FILE .java).json"

              curl -s https://api.openai.com/v1/chat/completions \
                -H "Authorization: Bearer $OPENAI_API_KEY" \
                -H "Content-Type: application/json" \
                -d '{
                  "model": "gpt-4",
                  "messages": [
                    {"role": "system", "content": "Eres un experto en Java Spring Boot que mejora el código según los problemas reportados por Sonar."},
                    {"role": "user", "content": "Este es el código (en base64): '"$CODE"'\n\nObservaciones Sonar: '"$REPORT"'"}
                  ],
                  "temperature": 0.3
                }' > "$RESPONSE_FILE"

              jq -r '.choices[0].message.content' "$RESPONSE_FILE" > "${FILE%.java}.mejorado.java"
              echo "Guardado: ${FILE%.java}.mejorado.java"
            else
              echo "Archivo no encontrado: $FILE"
            fi
          done < archivos_afectados.txt

      - name: Análisis de código mejorado
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          echo "Contenido actual:"
          ls -la

          if [ ! -d src ]; then
            echo "❌ No se encontró el directorio src/"
            exit 1
          fi

          cp -r src src-analizado

          for f in $(find src-analizado -name "*.mejorado.java"); do
            mv "$f" "${f%.mejorado.java}.java"
          done

          mvn sonar:sonar \
            -Dsonar.projectKey=rodrigorojasg_testSpring_gpt \
            -Dsonar.organization=rodrigorojasg \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.sources=src-analizado \
            -Dsonar.exclusions=src-analizado/test/** \
            -Dsonar.java.binaries=target/classes \
            -Dsonar.login=$SONAR_TOKEN > salida_sonar_gpt.txt

          echo "=== Salida de Sonar GPT ==="
          cat salida_sonar_gpt.txt

          errores_despues=$(grep -o 'severity":"[A-Z]\+"' salida_sonar_gpt.txt | wc -l)
          echo "ERRORES_DESPUES=$errores_despues" >> $GITHUB_ENV

      - name: Commit automático si hay mejora
        if: env.ERRORES_DESPUES < env.ERRORES_ANTES
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          iter_dir="ci-reportes/iteracion-${ITERACION_ACTUAL}"
          mkdir -p "$iter_dir"
          cp salida_sonar_original.txt "$iter_dir/sonar_original.txt" || true
          cp salida_sonar_gpt.txt "$iter_dir/sonar_mejorado.txt" || true
          cp reportes_ci/* "$iter_dir/" || true

          git add ci-reportes/
          git add src/**/*.mejorado.java || true
          git commit -m "🤖 Iteración ${ITERACION_ACTUAL}: mejora aplicada y reportes guardados"
          git push origin main
