name: Generar funcionalidad desde historia de usuario

on:
  push:
    paths:
      - 'historias-usuario/**.yml'

jobs:
  generar_codigo:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio actual
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          path: repositorio-base

      - name: Detectar historia de usuario modificada
        id: historia
        run: |
          cd repositorio-base
          git fetch --unshallow || true
          base_sha="${{ github.event.before }}"
          if ! git cat-file -e "$base_sha"^{commit} 2>/dev/null; then
            echo "⚠️ SHA base no válido o sin historial, usando HEAD^"
            base_sha="HEAD^"
          fi
          archivo=$(git diff --name-only "$base_sha" HEAD | grep '^historias-usuario/.*\.yml$' | head -n 1 || true)
          if [ -z "$archivo" ]; then
            echo "⛔ No se encontró ninguna historia de usuario modificada. Abortando."
            exit 1
          fi
          echo "ruta=$archivo" >> "$GITHUB_OUTPUT"

      - name: Leer historia y crear archivo de entrada
        run: |
          cd repositorio-base
          cat "${{ steps.historia.outputs.ruta }}" > entrada_gpt.txt

      - name: Instalar dependencias necesarias
        run: |
          sudo apt-get update
          sudo apt-get install -y jq unzip openjdk-17-jdk maven

      - name: Indexar clases y construir prompt
        run: |
          echo "📁 Buscando clases Java..."
          find repositorio-base/src/main/java -type f -name "*.java" > clases_existentes.txt
          if [ ! -s clases_existentes.txt ]; then
            echo "❌ No hay clases Java. Abortando."
            exit 1
          fi

          echo -e "\nClases detectadas en el repositorio base:" >> repositorio-base/entrada_gpt.txt
          cat clases_existentes.txt >> repositorio-base/entrada_gpt.txt

          echo -e "\n--- ANÁLISIS (Fase 1) ---" >> repositorio-base/entrada_gpt.txt
          echo "1. Qué clases pueden reutilizarse sin modificar." >> repositorio-base/entrada_gpt.txt
          echo "2. Qué clases deben ser modificadas (añadir métodos, anotaciones, etc.)." >> repositorio-base/entrada_gpt.txt
          echo "3. Qué clases deben ser nuevas." >> repositorio-base/entrada_gpt.txt

          echo -e "\n--- DISEÑO (Fase 2) ---" >> repositorio-base/entrada_gpt.txt
          echo "- Usa el contenido exacto de clases marcadas como modificables que aparece a continuación." >> repositorio-base/entrada_gpt.txt
          echo "- No elimines nada del contenido original. Solo agrega lo que se indica en la historia de usuario." >> repositorio-base/entrada_gpt.txt

          echo -e "\n--- CLASES COMPLETAS PARA MODIFICAR ---" >> repositorio-base/entrada_gpt.txt
          for path in $(cat clases_existentes.txt); do
            if grep -qE "public class (EmployeeController|EmployeeService|EmployeeServiceImpl|EmployeeRepository)" "$path"; then
              echo -e "\n// Inicio de clase original: $path\n" >> repositorio-base/entrada_gpt.txt
              cat "$path" >> repositorio-base/entrada_gpt.txt
              echo -e "\n// Fin de clase original: $path\n" >> repositorio-base/entrada_gpt.txt
            fi
          done

          echo -e "\n--- GENERACIÓN (Fase 3) ---" >> repositorio-base/entrada_gpt.txt
          echo "- Genera únicamente las clases nuevas o modificadas." >> repositorio-base/entrada_gpt.txt
          echo "- Usa exactamente el contenido original y agrega lo necesario." >> repositorio-base/entrada_gpt.txt
          echo "- No omitas métodos ni reemplaces clases enteras." >> repositorio-base/entrada_gpt.txt
          echo "- Cada clase comienza con 'package ...'. No incluyas explicaciones ni comentarios adicionales." >> repositorio-base/entrada_gpt.txt

      - name: Llamar a OpenAI para generar clases
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          cd repositorio-base
          PROMPT=$(cat entrada_gpt.txt)
          jq -n --arg prompt "$PROMPT" '{
            model: "gpt-4",
            messages: [
              { "role": "system", "content": "Eres un generador de código Java experto en Spring Boot. Usa solo clases válidas. Respeta código original si fue entregado." },
              { "role": "user", "content": $prompt }
            ],
            temperature: 0.3
          }' > payload.json

          curl -s https://api.openai.com/v1/chat/completions \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -H "Content-Type: application/json" \
            -d @payload.json > respuesta_gpt.json

          jq -r '.choices[0].message.content // "❌ No se encontró contenido válido."' respuesta_gpt.json > clases_generadas.java

      - name: Separar clases generadas
        run: |
          mkdir -p repositorio-base/src/main/java/ai/generated
          mkdir -p repositorio-base/src/test/java/ai/generated
          cd repositorio-base
          csplit --quiet --prefix=clase_ --suffix-format=%02d.java clases_generadas.java "/^package /" {*}
          i=1
          for file in clase_*.java; do
            class_name=$(grep -oP 'public\s+(class|interface|enum)\s+\K\w+' "$file" | head -n 1)
            if grep -q '@Test' "$file"; then
              dest="src/test/java/ai/generated"
            else
              dest="src/main/java/ai/generated"
            fi
            if [ -n "$class_name" ]; then
              mv "$file" "$dest/${class_name}.java"
            else
              mv "$file" "$dest/ClaseGenerada_$i.java"
            fi
            i=$((i+1))
          done

      - name: Ejecutar pruebas unitarias
        run: |
          cd repositorio-base
          mvn test || echo "⚠️ Algunos tests fallaron, revisar en GitHub Actions log"

      - name: Commit y push a nueva rama
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          cd repositorio-base
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git checkout -b feature/autogenerado-${{ github.run_id }}
          git add .
          if git diff --cached --quiet; then
            echo "⛔ No hay cambios para commitear, se omite push"
            exit 0
          fi
          git commit -m "🤖 Funcionalidad generada desde historia de usuario"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git
          git push origin HEAD
