name: Generar funcionalidad desde historia de usuario

on:
  push:
    paths:
      - 'historias-usuario/**.yml'

jobs:
  generar_codigo:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio actual
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          path: repositorio-base

      - name: Detectar historia de usuario modificada
        id: historia
        run: |
          cd repositorio-base
          git fetch --unshallow || true
          base_sha="${{ github.event.before }}"
          if ! git cat-file -e "$base_sha"^{commit} 2>/dev/null; then
            echo "⚠️ SHA base no válido o sin historial, usando HEAD^"
            base_sha="HEAD^"
          fi
          echo "🔍 Comparando con base: $base_sha"
          archivo=$(git diff --name-only "$base_sha" HEAD | grep '^historias-usuario/.*\.yml$' | head -n 1 || true)
          if [ -z "$archivo" ]; then
            echo "⛔ No se encontró ninguna historia de usuario modificada. Abortando."
            exit 1
          fi
          echo "ruta=$archivo" >> "$GITHUB_OUTPUT"

      - name: Leer contenido de historia de usuario
        run: |
          cd repositorio-base
          cat "${{ steps.historia.outputs.ruta }}" > entrada_gpt.txt

      - name: Instalar dependencias necesarias
        run: |
          sudo apt-get update
          sudo apt-get install -y jq unzip openjdk-17-jdk maven

      - name: Indexar clases Java existentes y preparar prompt
        run: |
          echo "📁 Buscando clases Java dentro de repositorio-base/src/main/java..."
          find repositorio-base/src/main/java -type f -name "*.java" > clases_existentes.txt
          if [ ! -s clases_existentes.txt ]; then
            echo "❌ No se encontraron archivos .java. Abortando."
            exit 1
          fi

          echo -e "\n\n--- HISTORIA DE USUARIO ---" > entrada_gpt.txt
          cat repositorio-base/"${{ steps.historia.outputs.ruta }}" >> entrada_gpt.txt

          echo -e "\n\n--- CLASES DETECTADAS EN EL REPOSITORIO BASE ---" >> entrada_gpt.txt
          cat clases_existentes.txt >> entrada_gpt.txt

          cat <<'EOF' >> entrada_gpt.txt

          --- ANÁLISIS DE CLASES EXISTENTES ---

          A continuación, entrega una tabla Markdown como esta:

          | Clase Java | Clasificación | Motivo |
          |------------|----------------|--------|
          | Employee | REUTILIZABLE-AS-IS | Ya contiene birthDate |
          | EmployeeServiceImpl | MODIFICABLE | Debe agregar lógica de validación para género |
          | NuevaClaseX | NUEVA | Se requiere nueva lógica para X |

          Solo incluye clases que ya existen en el proyecto o que deben crearse.

          --- INSTRUCCIONES DE MODIFICACIÓN ---

          1. Modifica solo las clases indicadas como MODIFICABLE, sin eliminar código anterior.
          2. Genera nuevas clases solo si están marcadas como NUEVA.
          3. No repitas ni sobrescribas clases existentes innecesariamente.

          --- CÓDIGO A GENERAR ---

          Devuelve únicamente el código Java correspondiente a las clases nuevas o modificadas. Cada clase debe comenzar con `package ...`.
          No incluyas comentarios explicativos ni texto adicional fuera del código.

          También incluye tests unitarios para validar la funcionalidad agregada.
          EOF

      - name: Mostrar tabla de diagnóstico (si existe)
        run: |
          echo "📋 Tabla de clases según GPT:"
          grep '|' repositorio-base/respuesta_gpt.json || echo "⚠️ GPT no generó tabla de diagnóstico"

      - name: Llamar a OpenAI para diagnóstico (solo análisis y clasificación)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          cd repositorio-base
          PROMPT=$(cat entrada_gpt.txt)

          jq -n --arg prompt "$PROMPT" '{
            model: "gpt-4",
            messages: [
              { "role": "system", "content": "Eres un analizador experto de código Java. Devuelve solo el análisis de clases existentes y el plan de modificación. No devuelvas código aún." },
              { "role": "user", "content": $prompt }
            ],
            temperature: 0.2
          }' > payload_diagnostico.json
          

          curl -s https://api.openai.com/v1/chat/completions \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -H "Content-Type: application/json" \
            -d @payload_diagnostico.json > respuesta_gpt_diagnostico.json

          echo "📨 Respuesta de OpenAI:"
          cat respuesta_gpt_diagnostico.json


          jq -r '.choices[0].message.content // "❌ GPT no devolvió contenido válido."' respuesta_gpt_diagnostico.json > diagnostico_gpt.txt

      - name: Mostrar análisis GPT
        run: |
          echo "📋 Tabla de diagnóstico de clases:"
          cat repositorio-base/diagnostico_gpt.txt || echo "⚠️ No se pudo leer diagnóstico"

      - name: Llamar a OpenAI para generación de código
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          cd repositorio-base

          PROMPT=$(cat entrada_gpt.txt)

          jq -n --arg prompt "$PROMPT" '{
            model: "gpt-4",
            messages: [
              { "role": "system", "content": "Eres un generador de código Java experto en Spring Boot. Solo devuelve clases y tests JUnit válidos. Cada bloque debe comenzar con \"package\". No incluyas texto adicional." },
              { "role": "user", "content": $prompt }
            ],
            temperature: 0.3
          }' > payload_generacion.json

          echo "🧾 Payload generado para OpenAI:"
          cat payload_generacion.json

          curl -s https://api.openai.com/v1/chat/completions \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -H "Content-Type: application/json" \
            -d @payload_generacion.json > respuesta_gpt.json

          echo "📨 Respuesta de OpenAI:"
          cat respuesta_gpt.json    


          jq -r '.choices[0].message.content // "❌ GPT no devolvió contenido válido."' respuesta_gpt.json > clases_generadas.java

      - name: Separar clases generadas
        run: |
          cd repositorio-base
          mkdir -p src/main/java/ai/generated
          mkdir -p src/test/java/ai/generated
          csplit --quiet --prefix=clase_ --suffix-format=%02d.java clases_generadas.java "/^package /" {*}
          i=1
          for file in clase_*.java; do
            class_name=$(grep -oP 'public\s+(class|interface|enum)\s+\K\w+' "$file" | head -n 1)
            if grep -q '@Test' "$file"; then
              dest="src/test/java/ai/generated"
            else
              dest="src/main/java/ai/generated"
            fi
            mv "$file" "$dest/${class_name:-ClaseGenerada_$i}.java"
            i=$((i+1))
          done

      - name: Ejecutar pruebas unitarias (incluye regresión)
        run: |
          cd repositorio-base
          mvn test || echo "⚠️ Algunos tests fallaron, revisar logs"

      - name: Commit y push de la nueva funcionalidad
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          cd repositorio-base
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git checkout -b feature/autogenerado-${{ github.run_id }}
          git add .
          if git diff --cached --quiet; then
            echo "⛔ No hay cambios para commitear, se omite push"
            exit 0
          fi
          git commit -m "🤖 Funcionalidad generada desde historia de usuario"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git
          git push origin HEAD
