name: Generar funcionalidad desde historia de usuario

on:
  push:
    paths:
      - 'historias-usuario/**.yml'

jobs:
  generar_codigo:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio actual
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          path: repositorio-base

      - name: Detectar historia de usuario modificada
        id: historia
        run: |
          cd repositorio-base
          git fetch --unshallow || true
          base_sha="${{ github.event.before }}"
          if ! git cat-file -e "$base_sha"^{commit} 2>/dev/null; then
            echo "⚠️ SHA base no válido o sin historial, usando HEAD^"
            base_sha="HEAD^"
          fi
          echo "🔍 Comparando con base: $base_sha"
          archivo=$(git diff --name-only "$base_sha" HEAD | grep '^historias-usuario/.*\.yml$' | head -n 1 || true)
          if [ -z "$archivo" ]; then
            echo "⛔ No se encontró ninguna historia de usuario modificada. Abortando."
            exit 1
          fi
          echo "📝 Historia modificada: $archivo"
          echo "ruta=$archivo" >> "$GITHUB_OUTPUT"

      - name: Leer contenido de historia de usuario
        run: |
          cd repositorio-base
          cat "${{ steps.historia.outputs.ruta }}" > entrada_gpt.txt

      - name: Instalar dependencias necesarias
        run: |
          sudo apt-get update
          sudo apt-get install -y jq unzip openjdk-17-jdk maven

      - name: Indexar clases Java existentes y preparar prompt
        run: |
          echo "📁 Buscando clases Java dentro de repositorio-base/src/main/java..."
          find repositorio-base/src/main/java -type f -name "*.java" > clases_existentes.txt

          if [ ! -s clases_existentes.txt ]; then
            echo "❌ No se encontraron archivos .java. Abortando."
            exit 1
          fi

          echo -e "\n--- Historia de usuario recibida ---\n" >> entrada_gpt.txt
          cat repositorio-base/"${{ steps.historia.outputs.ruta }}" >> entrada_gpt.txt

          echo -e "\n--- Clases existentes detectadas ---\n" >> entrada_gpt.txt
          while read -r ruta; do
            echo -e "\n--- Archivo: $ruta ---" >> entrada_gpt.txt
            cat "$ruta" >> entrada_gpt.txt
          done < clases_existentes.txt

          cat <<'EOF' >> entrada_gpt.txt

          --- ANÁLISIS (Fase 1) ---
          Indica:
          1. Qué clases pueden reutilizarse sin modificar.
          2. Qué clases deben ser modificadas (añadir métodos, anotaciones, endpoints, etc.).
          3. Qué clases deben ser completamente nuevas.

          --- PLAN (Fase 2) ---
          Para cada clase modificable:
          - Explica brevemente qué se agregará.
          - No elimines ni sobrescribas atributos ni métodos ya existentes.
          - Si agregas nuevos métodos, colócalos después del último método de la clase.
          - No uses comentarios como "Other methods...". Incluye todo el código original y lo nuevo.

          --- GENERACIÓN (Fase 3) ---
          Genera solo las clases nuevas o modificadas.
          Incluye el contenido completo de la clase (original + lo nuevo).
          Cada clase debe comenzar con 'package'.
          No incluyas explicaciones ni comentarios.

          EOF

          echo "🧠 Contenido final del prompt:"
          head -n 50 entrada_gpt.txt
          echo "... (prompt completo en logs del job)"

      - name: Llamar a OpenAI para generar clases y tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          cd repositorio-base
          PROMPT=$(cat entrada_gpt.txt)
          jq -n --arg prompt "$PROMPT" '{
            model: "gpt-4",
            messages: [
              { "role": "system", "content": "Eres un generador de código Java experto en Spring Boot. Solo devuelve clases y tests JUnit válidos, separados por líneas que comiencen con 'package'. No incluyas texto adicional." },
              { "role": "user", "content": $prompt }
            ],
            temperature: 0.3
          }' > payload.json

          curl -s https://api.openai.com/v1/chat/completions \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -H "Content-Type: application/json" \
            -d @payload.json > respuesta_gpt.json

          jq -r '.choices[0].message.content // "❌ No se encontró contenido válido en la respuesta de GPT."' respuesta_gpt.json > clases_generadas.java

      - name: Separar clases generadas
        run: |
          mkdir -p repositorio-base/src/main/java/ai/generated
          mkdir -p repositorio-base/src/test/java/ai/generated
          cd repositorio-base
          csplit --quiet --prefix=clase_ --suffix-format=%02d.java clases_generadas.java "/^package /" {*}
          i=1
          for file in clase_*.java; do
            class_name=$(grep -oP 'public\s+(class|interface|enum)\s+\K\w+' "$file" | head -n 1)
            if grep -q '@Test' "$file"; then
              dest="src/test/java/ai/generated"
            else
              dest="src/main/java/ai/generated"
            fi
            if [ -n "$class_name" ]; then
              mv "$file" "$dest/${class_name}.java"
            else
              mv "$file" "$dest/ClaseGenerada_$i.java"
            fi
            i=$((i+1))
          done

      - name: Ejecutar pruebas unitarias
        run: |
          cd repositorio-base
          mvn test || echo "⚠️ Algunos tests fallaron, revisar en GitHub Actions log"

      - name: Commit y push a nueva rama
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          cd repositorio-base
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git checkout -b feature/autogenerado-${{ github.run_id }}

          git add .
          if git diff --cached --quiet; then
            echo "⛔ No hay cambios para commitear, se omite push"
            exit 0
          fi

          git commit -m "🤖 Funcionalidad generada desde historia de usuario"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git
          git push origin HEAD
